language: ruby
rvm:
- 2.0.0
before_script:
- psql -c "create database dummy_test;" -U postgres
- psql -c "CREATE USER dummy WITH PASSWORD 'dummy';" -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: XvLApUuYpnEyRYT3IY6+07PERUGo8X7SnWXt8kkx/loQdPJ4xDoFoF+wIlCAOWQxc0pq3qWTB00ZTYFRyK1lcYrT2PLL5rAdSWpIHkcoivLzvKePH1cPcx0r+scKSufu9Ee5go02ZMkVmouoP0tw8NQeS4vK+q2uC6xJ8yJrYcU=
  gem: rubber_stamp
  on:
    repo: timothycommoner/rubber_stamp
